apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
type: Opaque
stringData:
  rclone.conf: |
    [minio]
    type = s3
    provider = Minio
    env_auth = false
    access_key_id = minioadmin
    secret_access_key = minioadmin
    endpoint = http://10.101.159.243:9000
    acl = private
    bucket_acl = private
